export const pagination ={
     data:[
         {
             id:1,
             image:'https://img.freepik.com/free-photo/driver-using-mobile-phone-navigation_53876-95136.jpg?size=626&ext=jpg',
             heading:'Discover the Marvels of Our World: The New Seven Wonders',
             location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
             text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
             text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
             text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
             text4:'prowess of humanity.',
             button:'Read more',
         },
         {  
            id:2,
            image:'https://img.freepik.com/free-photo/woman-traveling-with-her-car_23-2149076656.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:3,
            image:'https://img.freepik.com/free-photo/business-men-work-with-tablet-computers-their-cars_1359-1340.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:4,
            image:'https://img.freepik.com/free-photo/elegant-female-entrepreneur-get-car-drive-work-smiling-businesswoman-open-vehicle-door-looking-camera_197531-30463.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {  
            id:5,
            image:'https://img.freepik.com/premium-photo/positive-middle-eastern-woman-standing-by-car-showing-smartphone_116547-18486.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:6,
            image:'https://img.freepik.com/free-photo/handsome-bearded-businessman-white-shirt-speaking-by-phone-entering-his-car-while-standing-outdoors-streets-city-near-modern-office-center_496169-517.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:7,
            image:'https://img.freepik.com/free-photo/businesswoman-sitting-backseat-taxi_23-2149236711.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:8,
            image:'https://img.freepik.com/premium-psd/modern-futuristic-blue-podium-blue-background-high-quality_542670-243.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:9,
            image:'https://img.freepik.com/premium-photo/taxi-sign-city-map-with-stopwatch-route-concept-taxi-online-service-3d-illustration_505080-890.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:10,
            image:'https://img.freepik.com/premium-photo/blonde-woman-with-phone-street-european-city-eating-trdlo-praha_175356-4715.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        
     ]
 }