export const pagination ={
     data:[
         {
             id:1,
             image:'https://makejourneys.com/assets/images-listing/1675162684154-Seven-Wonders-World.jpg',
             heading:'Discover the Marvels of Our World: The New Seven Wonders',
             location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
             text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
             text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
             text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
             text4:'prowess of humanity.',
             button:'Read more',
         },
         {  
            id:2,
            image:'https://makejourneys.com/assets/images-listing/1675162684154-Seven-Wonders-World.jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:3,
            image:'https://makejourneys.com/assets/images-listing/1675162684154-Seven-Wonders-World.jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:4,
            image:'https://makejourneys.com/assets/images-listing/1675162684154-Seven-Wonders-World.jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {  
            id:5,
            image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShLFIKxlxYC7MAJyQPBT3M2eAxamkDHuyLgA&usqp=CAU',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:6,
            image:'https://makejourneys.com/assets/images-listing/1675162684154-Seven-Wonders-World.jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:7,
            image:'https://makejourneys.com/assets/images-listing/1675162684154-Seven-Wonders-World.jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:8,
            image:'https://makejourneys.com/assets/images-listing/1675162684154-Seven-Wonders-World.jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:9,
            image:'https://makejourneys.com/assets/images-listing/1675162684154-Seven-Wonders-World.jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:10,
            image:'https://makejourneys.com/assets/images-listing/1675162684154-Seven-Wonders-World.jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        
     ]
 }