export const pagination ={
     data:[
         {
             id:1,
             image:'https://img.freepik.com/free-photo/medical-stethoscope-with-paper-cut-family_23-2148488217.jpg?size=626&ext=jpg',
             heading:'Discover the Marvels of Our World: The New Seven Wonders',
             location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
             text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
             text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
             text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
             text4:'prowess of humanity.',
             button:'Read more',
         },
         {  
            id:2,
            image:'https://img.freepik.com/premium-photo/hospital-isometric-earth_258219-393.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:3,
            image:'https://img.freepik.com/premium-photo/3d-rendering-hospital-interior-with-lots-copy-space_190619-1588.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:4,
            image:'https://img.freepik.com/free-photo/doctor-helping-patient-during-rehabilitation_23-2150321595.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {  
            id:5,
            image:'https://img.freepik.com/free-photo/interior-modern-equipped-dental-office-with-x-ray-monitors-dentist-stomatology-orthodontic-workplace_482257-2309.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:6,
            image:'https://img.freepik.com/premium-photo/portrait-young-woman-wears-disposable-hat-gloves-medical-mask-poses-with-fingers-crossing_176532-158.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:7,
            image:'https://img.freepik.com/free-photo/beautiful-young-pretty-woman-with-healthy-skin-pink-flowers-close-face-isolated-white_186202-7858.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:8,
            image:'https://img.freepik.com/free-photo/team-young-specialist-doctors-standing-corridor-hospital_1303-21203.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:9,
            image:'https://img.freepik.com/free-photo/team-young-specialist-doctors-standing-corridor-hospital_1303-21203.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        {
            id:10,
            image:'https://img.freepik.com/free-photo/young-girl-pediatrician-s-office-physical-examination_23-2149187423.jpg?size=626&ext=jpg',
            heading:'Discover the Marvels of Our World: The New Seven Wonders',
            location:'https://cdn-icons-png.flaticon.com/512/9088/9088666.png',
            text1:'Traveling and exploring the world has always been a passion for many, and what better way to do so than to',
            text2:'witness some of the greatest marvels our world has to offer. The New Seven Wonders of the World are a list',
            text3:'of seven breathtaking structures, chosen from a list of 200, that showcase the talent, creativity, and technical',
            text4:'prowess of humanity.',
            button:'Read more',
        },
        
     ]
 }