name: Deploy

on:
  push:
    branches: ["edu7_vk8102"]
  pull_request:
    branches: ["edu7_vk8102"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            sudo chown -R $USER:$USER /var/www/techpyro-app
            sudo chmod +x /var/www/techpyro-app/.scripts/deploy.sh
            git config --global --add safe.directory /var/www/techpyro-app
            cd /var/www/techpyro-app
            ./.scripts/deploy.sh
