name: React App CI/CD

on:
  push:
    branches: [ "university9" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.16.0]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build
      run: npm run build
      env:
        CI: false

    # Optional step: deploy if build is successfully
    # - name: Deploy (optional)
    #   run: echo "your deploy step"
